- name: Send email every 30 seconds
  run: |
    for i in {1..2}; do
      echo "Sending email at $(date)";
      echo "Subject: Half-minute Message" | sendmail raydingwang@gmail.com;
      sleep 30;
    done
